// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dependency "github.com/ldassonville/crossplane-assistant/internal/crossplane/innervision/composition/dependency"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/crossplane/crossplane/apis/apiextensions/v1"
)

// CompositionService is an autogenerated mock type for the CompositionService type
type CompositionService struct {
	mock.Mock
}

type CompositionService_Expecter struct {
	mock *mock.Mock
}

func (_m *CompositionService) EXPECT() *CompositionService_Expecter {
	return &CompositionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *CompositionService) Create(ctx context.Context, _a1 *v1.Composition) (*v1.Composition, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.Composition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition) (*v1.Composition, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition) *v1.Composition); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Composition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Composition) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CompositionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Composition
func (_e *CompositionService_Expecter) Create(ctx interface{}, _a1 interface{}) *CompositionService_Create_Call {
	return &CompositionService_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *CompositionService_Create_Call) Run(run func(ctx context.Context, _a1 *v1.Composition)) *CompositionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Composition))
	})
	return _c
}

func (_c *CompositionService_Create_Call) Return(_a0 *v1.Composition, _a1 error) *CompositionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompositionService_Create_Call) RunAndReturn(run func(context.Context, *v1.Composition) (*v1.Composition, error)) *CompositionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name
func (_m *CompositionService) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompositionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CompositionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *CompositionService_Expecter) Delete(ctx interface{}, name interface{}) *CompositionService_Delete_Call {
	return &CompositionService_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *CompositionService_Delete_Call) Run(run func(ctx context.Context, name string)) *CompositionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CompositionService_Delete_Call) Return(_a0 error) *CompositionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompositionService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *CompositionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name
func (_m *CompositionService) Get(ctx context.Context, name string) (*v1.Composition, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.Composition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1.Composition, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.Composition); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Composition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CompositionService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *CompositionService_Expecter) Get(ctx interface{}, name interface{}) *CompositionService_Get_Call {
	return &CompositionService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *CompositionService_Get_Call) Run(run func(ctx context.Context, name string)) *CompositionService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CompositionService_Get_Call) Return(_a0 *v1.Composition, _a1 error) *CompositionService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompositionService_Get_Call) RunAndReturn(run func(context.Context, string) (*v1.Composition, error)) *CompositionService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetDependencies provides a mock function with given fields: ctx, name
func (_m *CompositionService) GetDependencies(ctx context.Context, name string) (*dependency.ResourceGraph, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencies")
	}

	var r0 *dependency.ResourceGraph
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dependency.ResourceGraph, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dependency.ResourceGraph); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dependency.ResourceGraph)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionService_GetDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDependencies'
type CompositionService_GetDependencies_Call struct {
	*mock.Call
}

// GetDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *CompositionService_Expecter) GetDependencies(ctx interface{}, name interface{}) *CompositionService_GetDependencies_Call {
	return &CompositionService_GetDependencies_Call{Call: _e.mock.On("GetDependencies", ctx, name)}
}

func (_c *CompositionService_GetDependencies_Call) Run(run func(ctx context.Context, name string)) *CompositionService_GetDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CompositionService_GetDependencies_Call) Return(_a0 *dependency.ResourceGraph, _a1 error) *CompositionService_GetDependencies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompositionService_GetDependencies_Call) RunAndReturn(run func(context.Context, string) (*dependency.ResourceGraph, error)) *CompositionService_GetDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *CompositionService) List(ctx context.Context) (*v1.CompositionList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.CompositionList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*v1.CompositionList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *v1.CompositionList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CompositionList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CompositionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CompositionService_Expecter) List(ctx interface{}) *CompositionService_List_Call {
	return &CompositionService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *CompositionService_List_Call) Run(run func(ctx context.Context)) *CompositionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CompositionService_List_Call) Return(_a0 *v1.CompositionList, _a1 error) *CompositionService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompositionService_List_Call) RunAndReturn(run func(context.Context) (*v1.CompositionList, error)) *CompositionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *CompositionService) Update(ctx context.Context, _a1 *v1.Composition) (*v1.Composition, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.Composition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition) (*v1.Composition, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition) *v1.Composition); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Composition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Composition) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CompositionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Composition
func (_e *CompositionService_Expecter) Update(ctx interface{}, _a1 interface{}) *CompositionService_Update_Call {
	return &CompositionService_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *CompositionService_Update_Call) Run(run func(ctx context.Context, _a1 *v1.Composition)) *CompositionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Composition))
	})
	return _c
}

func (_c *CompositionService_Update_Call) Return(_a0 *v1.Composition, _a1 error) *CompositionService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompositionService_Update_Call) RunAndReturn(run func(context.Context, *v1.Composition) (*v1.Composition, error)) *CompositionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompositionService creates a new instance of CompositionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompositionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompositionService {
	mock := &CompositionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
