// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "github.com/crossplane/crossplane/apis/apiextensions/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// CompositionInterface is an autogenerated mock type for the CompositionInterface type
type CompositionInterface struct {
	mock.Mock
}

type CompositionInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *CompositionInterface) EXPECT() *CompositionInterface_Expecter {
	return &CompositionInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, node, opts
func (_m *CompositionInterface) Create(ctx context.Context, node *v1.Composition, opts metav1.CreateOptions) (*v1.Composition, error) {
	ret := _m.Called(ctx, node, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.Composition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition, metav1.CreateOptions) (*v1.Composition, error)); ok {
		return rf(ctx, node, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition, metav1.CreateOptions) *v1.Composition); ok {
		r0 = rf(ctx, node, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Composition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Composition, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, node, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CompositionInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - node *v1.Composition
//   - opts metav1.CreateOptions
func (_e *CompositionInterface_Expecter) Create(ctx interface{}, node interface{}, opts interface{}) *CompositionInterface_Create_Call {
	return &CompositionInterface_Create_Call{Call: _e.mock.On("Create", ctx, node, opts)}
}

func (_c *CompositionInterface_Create_Call) Run(run func(ctx context.Context, node *v1.Composition, opts metav1.CreateOptions)) *CompositionInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Composition), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *CompositionInterface_Create_Call) Return(result *v1.Composition, err error) *CompositionInterface_Create_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *CompositionInterface_Create_Call) RunAndReturn(run func(context.Context, *v1.Composition, metav1.CreateOptions) (*v1.Composition, error)) *CompositionInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *CompositionInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompositionInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CompositionInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *CompositionInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *CompositionInterface_Delete_Call {
	return &CompositionInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *CompositionInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *CompositionInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *CompositionInterface_Delete_Call) Return(_a0 error) *CompositionInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompositionInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *CompositionInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *CompositionInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompositionInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type CompositionInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *CompositionInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *CompositionInterface_DeleteCollection_Call {
	return &CompositionInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *CompositionInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *CompositionInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *CompositionInterface_DeleteCollection_Call) Return(_a0 error) *CompositionInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompositionInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *CompositionInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, options
func (_m *CompositionInterface) Get(ctx context.Context, name string, options metav1.GetOptions) (*v1.Composition, error) {
	ret := _m.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.Composition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.Composition, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.Composition); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Composition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CompositionInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options metav1.GetOptions
func (_e *CompositionInterface_Expecter) Get(ctx interface{}, name interface{}, options interface{}) *CompositionInterface_Get_Call {
	return &CompositionInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, options)}
}

func (_c *CompositionInterface_Get_Call) Run(run func(ctx context.Context, name string, options metav1.GetOptions)) *CompositionInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *CompositionInterface_Get_Call) Return(result *v1.Composition, err error) *CompositionInterface_Get_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *CompositionInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.Composition, error)) *CompositionInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *CompositionInterface) List(ctx context.Context, opts metav1.ListOptions) (*v1.CompositionList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.CompositionList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*v1.CompositionList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *v1.CompositionList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CompositionList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CompositionInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *CompositionInterface_Expecter) List(ctx interface{}, opts interface{}) *CompositionInterface_List_Call {
	return &CompositionInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *CompositionInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *CompositionInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *CompositionInterface_List_Call) Return(result *v1.CompositionList, err error) *CompositionInterface_List_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *CompositionInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*v1.CompositionList, error)) *CompositionInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, node, opts
func (_m *CompositionInterface) Update(ctx context.Context, node *v1.Composition, opts metav1.UpdateOptions) (*v1.Composition, error) {
	ret := _m.Called(ctx, node, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.Composition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition, metav1.UpdateOptions) (*v1.Composition, error)); ok {
		return rf(ctx, node, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition, metav1.UpdateOptions) *v1.Composition); ok {
		r0 = rf(ctx, node, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Composition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Composition, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, node, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CompositionInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - node *v1.Composition
//   - opts metav1.UpdateOptions
func (_e *CompositionInterface_Expecter) Update(ctx interface{}, node interface{}, opts interface{}) *CompositionInterface_Update_Call {
	return &CompositionInterface_Update_Call{Call: _e.mock.On("Update", ctx, node, opts)}
}

func (_c *CompositionInterface_Update_Call) Run(run func(ctx context.Context, node *v1.Composition, opts metav1.UpdateOptions)) *CompositionInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Composition), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *CompositionInterface_Update_Call) Return(result *v1.Composition, err error) *CompositionInterface_Update_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *CompositionInterface_Update_Call) RunAndReturn(run func(context.Context, *v1.Composition, metav1.UpdateOptions) (*v1.Composition, error)) *CompositionInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, node, opts
func (_m *CompositionInterface) UpdateStatus(ctx context.Context, node *v1.Composition, opts metav1.UpdateOptions) (*v1.Composition, error) {
	ret := _m.Called(ctx, node, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *v1.Composition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition, metav1.UpdateOptions) (*v1.Composition, error)); ok {
		return rf(ctx, node, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Composition, metav1.UpdateOptions) *v1.Composition); ok {
		r0 = rf(ctx, node, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Composition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Composition, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, node, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type CompositionInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - node *v1.Composition
//   - opts metav1.UpdateOptions
func (_e *CompositionInterface_Expecter) UpdateStatus(ctx interface{}, node interface{}, opts interface{}) *CompositionInterface_UpdateStatus_Call {
	return &CompositionInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, node, opts)}
}

func (_c *CompositionInterface_UpdateStatus_Call) Run(run func(ctx context.Context, node *v1.Composition, opts metav1.UpdateOptions)) *CompositionInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Composition), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *CompositionInterface_UpdateStatus_Call) Return(result *v1.Composition, err error) *CompositionInterface_UpdateStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *CompositionInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *v1.Composition, metav1.UpdateOptions) (*v1.Composition, error)) *CompositionInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *CompositionInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompositionInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type CompositionInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *CompositionInterface_Expecter) Watch(ctx interface{}, opts interface{}) *CompositionInterface_Watch_Call {
	return &CompositionInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *CompositionInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *CompositionInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *CompositionInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *CompositionInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompositionInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *CompositionInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompositionInterface creates a new instance of CompositionInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompositionInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompositionInterface {
	mock := &CompositionInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
