// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	claim "github.com/ldassonville/crossplane-assistant/internal/crossplane/innervision/claim"

	mock "github.com/stretchr/testify/mock"

	unstruct "github.com/ldassonville/crossplane-assistant/internal/crossplane/innervision/unstruct"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	unstructuredclaim "github.com/crossplane/crossplane-runtime/pkg/resource/unstructured/claim"
)

// ClaimService is an autogenerated mock type for the ClaimService type
type ClaimService struct {
	mock.Mock
}

type ClaimService_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimService) EXPECT() *ClaimService_Expecter {
	return &ClaimService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *ClaimService) Create(ctx context.Context, _a1 *unstructured.Unstructured) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured) *unstructured.Unstructured); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstructured.Unstructured) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClaimService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *unstructured.Unstructured
func (_e *ClaimService_Expecter) Create(ctx interface{}, _a1 interface{}) *ClaimService_Create_Call {
	return &ClaimService_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *ClaimService_Create_Call) Run(run func(ctx context.Context, _a1 *unstructured.Unstructured)) *ClaimService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured))
	})
	return _c
}

func (_c *ClaimService_Create_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *ClaimService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimService_Create_Call) RunAndReturn(run func(context.Context, *unstructured.Unstructured) (*unstructured.Unstructured, error)) *ClaimService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ref
func (_m *ClaimService) Delete(ctx context.Context, ref *unstruct.ResourceRef) error {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstruct.ResourceRef) error); ok {
		r0 = rf(ctx, ref)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ClaimService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ref *unstruct.ResourceRef
func (_e *ClaimService_Expecter) Delete(ctx interface{}, ref interface{}) *ClaimService_Delete_Call {
	return &ClaimService_Delete_Call{Call: _e.mock.On("Delete", ctx, ref)}
}

func (_c *ClaimService_Delete_Call) Run(run func(ctx context.Context, ref *unstruct.ResourceRef)) *ClaimService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstruct.ResourceRef))
	})
	return _c
}

func (_c *ClaimService_Delete_Call) Return(_a0 error) *ClaimService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClaimService_Delete_Call) RunAndReturn(run func(context.Context, *unstruct.ResourceRef) error) *ClaimService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, ref
func (_m *ClaimService) Get(ctx context.Context, ref *unstruct.ResourceRef) (*unstructuredclaim.Unstructured, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *unstructuredclaim.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstruct.ResourceRef) (*unstructuredclaim.Unstructured, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstruct.ResourceRef) *unstructuredclaim.Unstructured); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructuredclaim.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstruct.ResourceRef) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClaimService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ref *unstruct.ResourceRef
func (_e *ClaimService_Expecter) Get(ctx interface{}, ref interface{}) *ClaimService_Get_Call {
	return &ClaimService_Get_Call{Call: _e.mock.On("Get", ctx, ref)}
}

func (_c *ClaimService_Get_Call) Run(run func(ctx context.Context, ref *unstruct.ResourceRef)) *ClaimService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstruct.ResourceRef))
	})
	return _c
}

func (_c *ClaimService_Get_Call) Return(_a0 *unstructuredclaim.Unstructured, _a1 error) *ClaimService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimService_Get_Call) RunAndReturn(run func(context.Context, *unstruct.ResourceRef) (*unstructuredclaim.Unstructured, error)) *ClaimService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourcesTree provides a mock function with given fields: ctx, ref
func (_m *ClaimService) GetResourcesTree(ctx context.Context, ref *unstruct.ResourceRef) (*claim.Tree, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetResourcesTree")
	}

	var r0 *claim.Tree
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstruct.ResourceRef) (*claim.Tree, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstruct.ResourceRef) *claim.Tree); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*claim.Tree)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstruct.ResourceRef) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimService_GetResourcesTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourcesTree'
type ClaimService_GetResourcesTree_Call struct {
	*mock.Call
}

// GetResourcesTree is a helper method to define mock.On call
//   - ctx context.Context
//   - ref *unstruct.ResourceRef
func (_e *ClaimService_Expecter) GetResourcesTree(ctx interface{}, ref interface{}) *ClaimService_GetResourcesTree_Call {
	return &ClaimService_GetResourcesTree_Call{Call: _e.mock.On("GetResourcesTree", ctx, ref)}
}

func (_c *ClaimService_GetResourcesTree_Call) Run(run func(ctx context.Context, ref *unstruct.ResourceRef)) *ClaimService_GetResourcesTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstruct.ResourceRef))
	})
	return _c
}

func (_c *ClaimService_GetResourcesTree_Call) Return(_a0 *claim.Tree, _a1 error) *ClaimService_GetResourcesTree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimService_GetResourcesTree_Call) RunAndReturn(run func(context.Context, *unstruct.ResourceRef) (*claim.Tree, error)) *ClaimService_GetResourcesTree_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *ClaimService) List(ctx context.Context, opts *claim.ListOpt) ([]unstructuredclaim.Unstructured, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []unstructuredclaim.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *claim.ListOpt) ([]unstructuredclaim.Unstructured, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *claim.ListOpt) []unstructuredclaim.Unstructured); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]unstructuredclaim.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *claim.ListOpt) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ClaimService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *claim.ListOpt
func (_e *ClaimService_Expecter) List(ctx interface{}, opts interface{}) *ClaimService_List_Call {
	return &ClaimService_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *ClaimService_List_Call) Run(run func(ctx context.Context, opts *claim.ListOpt)) *ClaimService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*claim.ListOpt))
	})
	return _c
}

func (_c *ClaimService_List_Call) Return(_a0 []unstructuredclaim.Unstructured, _a1 error) *ClaimService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimService_List_Call) RunAndReturn(run func(context.Context, *claim.ListOpt) ([]unstructuredclaim.Unstructured, error)) *ClaimService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *ClaimService) Update(ctx context.Context, _a1 *unstructured.Unstructured) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured) *unstructured.Unstructured); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstructured.Unstructured) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ClaimService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *unstructured.Unstructured
func (_e *ClaimService_Expecter) Update(ctx interface{}, _a1 interface{}) *ClaimService_Update_Call {
	return &ClaimService_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *ClaimService_Update_Call) Run(run func(ctx context.Context, _a1 *unstructured.Unstructured)) *ClaimService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured))
	})
	return _c
}

func (_c *ClaimService_Update_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *ClaimService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimService_Update_Call) RunAndReturn(run func(context.Context, *unstructured.Unstructured) (*unstructured.Unstructured, error)) *ClaimService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimService creates a new instance of ClaimService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimService {
	mock := &ClaimService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
