package claim

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/ldassonville/crossplane-assistant/internal/crossplane/innervision/unstruct"
	"strings"

	"github.com/crossplane/crossplane-runtime/pkg/resource/unstructured/claim"
	"github.com/crossplane/crossplane-runtime/pkg/resource/unstructured/composite"
	v12 "github.com/crossplane/crossplane/apis/apiextensions/v1"
	compositionv1 "github.com/ldassonville/crossplane-assistant/internal/crossplane/client/apiextentions/v1"
	"github.com/ldassonville/crossplane-assistant/internal/crossplane/client/kubernetes/v1alpha1"
	"github.com/ldassonville/crossplane-assistant/internal/kube/resource"
	"github.com/rs/zerolog/log"
	crdv1 "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/dynamic"
)

// KubernetesProviderClient is the minimal surface of *v1alpha1.KubernetesV1AlphaClient
// that Service depends on, so tests can substitute a fake without constructing
// a real REST-backed client.
type KubernetesProviderClient interface {
	Objects() v1alpha1.ObjectInterface
}

// ClaimService is the interface Handler depends on, implemented by Service.
type ClaimService interface {
	List(ctx context.Context, opts *ListOpt) ([]claim.Unstructured, error)
	Get(ctx context.Context, ref *unstruct.ResourceRef) (*claim.Unstructured, error)
	GetResourcesTree(ctx context.Context, ref *unstruct.ResourceRef) (*Tree, error)
	Create(ctx context.Context, unstructured *unstructured.Unstructured) (*unstructured.Unstructured, error)
	Update(ctx context.Context, unstructured *unstructured.Unstructured) (*unstructured.Unstructured, error)
	Delete(ctx context.Context, ref *unstruct.ResourceRef) error
}

func NewClaimService(
	xrdItf compositionv1.CompositeResourceDefinitionsInterface,
	crdClient crdv1.CustomResourceDefinitionInterface,
	crdRegistry *resource.CRDRegistry,
	discoveryClient discovery.DiscoveryInterface,
	dynamicClient dynamic.Interface,
	xK8sProviderClient KubernetesProviderClient,
	resourceResolver *unstruct.ResourceResolver,

) *Service {

	return &Service{
		xrdClient:          xrdItf,
		crdClient:          crdClient,
		crdRegistry:        crdRegistry,
		dynamicClient:      dynamicClient,
		discoveryCli:       discoveryClient,
		xK8sProviderClient: xK8sProviderClient,
		resourceResolver:   resourceResolver,
	}
}

type Service struct {
	xrdClient          compositionv1.CompositeResourceDefinitionsInterface
	crdRegistry        *resource.CRDRegistry
	crdClient          crdv1.CustomResourceDefinitionInterface
	discoveryCli       discovery.DiscoveryInterface
	dynamicClient      dynamic.Interface
	xK8sProviderClient KubernetesProviderClient
	resourceResolver   *unstruct.ResourceResolver
}

type ListOpt struct {
	Kinds             []string
	HideManagedFields bool
}

func (s *Service) filterXRD(xrdList []v12.CompositeResourceDefinition, kinds []string) []v12.CompositeResourceDefinition {

	var res []v12.CompositeResourceDefinition

	for _, xrd := range xrdList {
		for _, kind := range kinds {
			if strings.EqualFold(xrd.Spec.ClaimNames.Kind, kind) {
				res = append(res, xrd)
			}
		}
	}
	return res
}

// List all the claim resources present in the cluster
// that are matching the options
func (s *Service) List(ctx context.Context, opts *ListOpt) ([]claim.Unstructured, error) {

	var res []claim.Unstructured

	// Get all the composite resource definitions
	compositeResourceDef, err := s.xrdClient.List(ctx, metav1.ListOptions{})
	if err != nil {
		log.Err(err).Msgf("Fail to get composite resource definitions")
		return nil, err
	}

	var xrdList = compositeResourceDef.Items
	if opts != nil && len(opts.Kinds) > 0 {
		xrdList = s.filterXRD(xrdList, opts.Kinds)
	}

	// Resolve all the resources
	for _, composition := range xrdList {

		// Discover the crd generated by the xrd
		crd, err := s.crdRegistry.Get(composition.Spec.ClaimNames.Plural + "." + composition.Spec.Group)
		if err != nil {
			log.Err(err).Msgf("Fail to get crd %s", composition.Spec.ClaimNames.Plural)
			continue
		}

		// Resolving the manifest for the given crd
		clientResource := s.dynamicClient.Resource(schema.GroupVersionResource{
			Group:    crd.Spec.Group,
			Version:  crd.Spec.Versions[0].Name,
			Resource: crd.Spec.Names.Plural,
		})

		unstructuredList, err := clientResource.List(ctx, metav1.ListOptions{})
		if err != nil {
			log.Err(err).Msgf("Fail to get crd %s", composition.Spec.ClaimNames.Plural)
			continue
		}

		// Append the resources to the result list
		for _, item := range unstructuredList.Items {
			res = append(res, claim.Unstructured{
				Unstructured: item,
			})
		}
	}

	// Hide managed fields from the resources
	if opts != nil && opts.HideManagedFields {
		for _, item := range res {
			item.SetManagedFields(nil)
		}
	}

	return res, nil
}

// Get a claim resource by name
func (s *Service) Get(ctx context.Context, ref *unstruct.ResourceRef) (*claim.Unstructured, error) {

	cr, err := s.resourceResolver.ResolveUnstructuredResources(ctx, ref.APIVersion, ref.Kind, ref.Namespace, ref.Name)
	if err != nil {
		return nil, err
	}
	return &claim.Unstructured{
		Unstructured: *cr,
	}, nil
}

// TODO : Refactor this method and split it into smaller methods
func (s *Service) GetResourcesTree(ctx context.Context, ref *unstruct.ResourceRef) (*Tree, error) {

	tree := &Tree{
		Root: &Node{
			Version:   ref.APIVersion,
			Kind:      ref.Kind,
			Namespace: ref.Namespace,
			Name:      ref.Name,
			MetaKind:  "XRC",
		},
	}

	// Step 1: Get the claim resource
	claimResource, err := s.resourceResolver.ResolveUnstructuredResources(ctx, ref.APIVersion, ref.Kind, ref.Namespace, ref.Name)
	if err != nil {
		return nil, err
	}

	// Step 2: Get the composition resource
	c := claim.Unstructured{
		Unstructured: *claimResource,
	}
	tree.Root.Uid = fmt.Sprintf("%v", c.GetUID())
	tree.Root.Manifest = &c

	compositeRef := c.GetResourceReference()

	if compositeRef == nil {
		return tree, nil
	}

	resourceRef, err := s.resourceResolver.ResolveUnstructuredResources(ctx, compositeRef.APIVersion, compositeRef.Kind, compositeRef.Namespace, compositeRef.Name)
	if err != nil {
		return nil, err
	}

	compositeEntity := composite.Unstructured{
		Unstructured: *resourceRef,
	}

	compositeNode := tree.Root.AddChild(&Node{
		Version:   compositeEntity.GetAPIVersion(),
		Kind:      compositeEntity.GetKind(),
		Namespace: compositeEntity.GetNamespace(),
		Name:      compositeEntity.GetName(),
		Uid:       fmt.Sprintf("%v", compositeEntity.GetUID()),
		MetaKind:  "XR",
		Manifest:  &compositeEntity,
	})

	for i, ref := range compositeEntity.GetResourceReferences() {

		refNode := &Node{
			Version:   ref.APIVersion,
			Kind:      ref.Kind,
			Namespace: ref.Namespace,
			Name:      ref.Name,
			MetaKind:  "Resource",
			Index:     &i,
		}
		compositeNode.AddChild(refNode)

		if ref.Kind == "Object" && strings.HasPrefix(ref.APIVersion, "kubernetes.crossplane.io") {

			object, err := s.xK8sProviderClient.Objects().Get(ctx, ref.Name, metav1.GetOptions{})
			if err != nil {
				log.Err(err).Msgf("Fail to get object %s:%s %s", ref.APIVersion, ref.Kind, ref.Name)
				continue
			}

			object.Kind = ref.Kind
			object.APIVersion = ref.APIVersion

			// Enrich the node with the object information
			refNode.Uid = fmt.Sprintf("%v", object.GetUID())
			refNode.Manifest = object
			refNode.ResourceVersion = object.GetResourceVersion()
			refNode.Generation = object.GetGeneration()

			for _, c := range object.Status.Conditions {
				refNode.Conditions = append(refNode.Conditions, Condition{
					Type:    string(c.Type),
					Status:  string(c.Status),
					Reason:  string(c.Reason),
					Message: c.Message,
				})
			}

			providerManifest := object.Status.AtProvider.Manifest

			manifestInfo := &KubernetesManifest{}
			if err := json.Unmarshal(providerManifest.Raw, manifestInfo); err != nil {
				continue
			}

			k8sManifest, err := s.resourceResolver.ResolveUnstructuredResources(ctx, manifestInfo.APIVersion, manifestInfo.Kind, manifestInfo.Namespace, manifestInfo.Name)
			if err != nil {
				log.Err(err).Msgf("Fail to get resource %s", ref.Name)
				continue
			}

			refNode.AddChild(&Node{
				Version:   k8sManifest.GetAPIVersion(),
				Kind:      k8sManifest.GetKind(),
				Namespace: k8sManifest.GetNamespace(),
				Name:      k8sManifest.GetName(),
				Uid:       fmt.Sprintf("%v", object.GetUID()),
				MetaKind:  "Manifest",
				Manifest:  k8sManifest,
			})

		} else {

			// Default generic resource
			object, err := s.resourceResolver.ResolveUnstructuredResources(ctx, ref.APIVersion, ref.Kind, ref.Namespace, ref.Name)
			if err != nil {
				log.Warn().Err(err).Msgf("Fail to get unstructed resource %s", ref.Name)
				continue
			}

			refNode.Uid = fmt.Sprintf("%v", object.GetUID())
			refNode.Manifest = object
			refNode.ResourceVersion = object.GetResourceVersion()
			refNode.Generation = object.GetGeneration()
		}
	}

	// Step 03 :

	return tree, nil
}

type KubernetesManifest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
}

func (s *Service) Create(ctx context.Context, unstructured *unstructured.Unstructured) (*unstructured.Unstructured, error) {

	clientResource, err := s.resourceResolver.GetClient(unstructured.GetAPIVersion(), unstructured.GetKind())
	if err != nil {
		return nil, err
	}

	res, err := clientResource.Namespace(unstructured.GetNamespace()).Create(ctx, unstructured, metav1.CreateOptions{})
	return res, err
}

func (s *Service) Update(ctx context.Context, unstructured *unstructured.Unstructured) (*unstructured.Unstructured, error) {

	clientResource, err := s.resourceResolver.GetClient(unstructured.GetAPIVersion(), unstructured.GetKind())
	if err != nil {
		return nil, err
	}

	composition, err := clientResource.Update(ctx, unstructured, metav1.UpdateOptions{})
	return composition, err
}

func (s *Service) Delete(ctx context.Context, ref *unstruct.ResourceRef) error {

	clientResource, err := s.resourceResolver.GetClient(ref.APIVersion, ref.Kind)
	if err != nil {
		return err
	}

	err = clientResource.Namespace(ref.Namespace).Delete(ctx, ref.Name, metav1.DeleteOptions{})
	return err
}
