// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	diagnostic "github.com/ldassonville/crossplane-assistant/internal/crossplane/innervision/diagnostic"
	mock "github.com/stretchr/testify/mock"

	unstruct "github.com/ldassonville/crossplane-assistant/internal/crossplane/innervision/unstruct"
)

// DiagnosticService is an autogenerated mock type for the DiagnosticService type
type DiagnosticService struct {
	mock.Mock
}

type DiagnosticService_Expecter struct {
	mock *mock.Mock
}

func (_m *DiagnosticService) EXPECT() *DiagnosticService_Expecter {
	return &DiagnosticService_Expecter{mock: &_m.Mock}
}

// GetClaimDiagnostics provides a mock function with given fields: ctx, ref
func (_m *DiagnosticService) GetClaimDiagnostics(ctx context.Context, ref *unstruct.ResourceRef) (*diagnostic.DiagnosticResponse, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimDiagnostics")
	}

	var r0 *diagnostic.DiagnosticResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstruct.ResourceRef) (*diagnostic.DiagnosticResponse, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *unstruct.ResourceRef) *diagnostic.DiagnosticResponse); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*diagnostic.DiagnosticResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *unstruct.ResourceRef) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiagnosticService_GetClaimDiagnostics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimDiagnostics'
type DiagnosticService_GetClaimDiagnostics_Call struct {
	*mock.Call
}

// GetClaimDiagnostics is a helper method to define mock.On call
//   - ctx context.Context
//   - ref *unstruct.ResourceRef
func (_e *DiagnosticService_Expecter) GetClaimDiagnostics(ctx interface{}, ref interface{}) *DiagnosticService_GetClaimDiagnostics_Call {
	return &DiagnosticService_GetClaimDiagnostics_Call{Call: _e.mock.On("GetClaimDiagnostics", ctx, ref)}
}

func (_c *DiagnosticService_GetClaimDiagnostics_Call) Run(run func(ctx context.Context, ref *unstruct.ResourceRef)) *DiagnosticService_GetClaimDiagnostics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstruct.ResourceRef))
	})
	return _c
}

func (_c *DiagnosticService_GetClaimDiagnostics_Call) Return(_a0 *diagnostic.DiagnosticResponse, _a1 error) *DiagnosticService_GetClaimDiagnostics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DiagnosticService_GetClaimDiagnostics_Call) RunAndReturn(run func(context.Context, *unstruct.ResourceRef) (*diagnostic.DiagnosticResponse, error)) *DiagnosticService_GetClaimDiagnostics_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiagnosticService creates a new instance of DiagnosticService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiagnosticService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiagnosticService {
	mock := &DiagnosticService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
